CREATE TABLE IF NOT EXISTS room_users(
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    roleid INT NOT NULL DEFAULT 1 REFERENCES roles(roleid) ON DELETE SET DEFAULT,
    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY(room_id, user_id)
)

