CREATE TABLE IF NOT EXISTS join_tokens(
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    roleid INT NOT NULL DEFAULT 1 REFERENCES roles(roleid) ON DELETE SET DEFAULT,
    token BYTEA NOT NULL UNIQUE,
    expiry TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS user_tokens(
    userid BIGINT NOT NULL,
    token BYTEA NOT NULL UNIQUE,
    expiry TIMESTAMPTZ NOT NULL
);